#!/bin/bash
echo "=== Installing MongoDB ==="
echo ""
echo "Option 1: Install MongoDB Community Edition (Recommended)"
echo "Run these commands:"
echo ""
echo "  # Import MongoDB public GPG key"
echo "  wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -"
echo ""
echo "  # Add MongoDB repository"
echo "  echo \"deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu \$(lsb_release -cs)/mongodb-org/7.0 multiverse\" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list"
echo ""
echo "  # Update and install"
echo "  sudo apt-get update"
echo "  sudo apt-get install -y mongodb-org"
echo ""
echo "  # Start MongoDB"
echo "  sudo systemctl start mongod"
echo "  sudo systemctl enable mongod"
echo ""
echo "Option 2: Use MongoDB Atlas (Cloud - Free tier available)"
echo "  Visit: https://www.mongodb.com/cloud/atlas"
echo "  Create a free cluster and update MONGODB_URI in .env file"
echo ""
